
language: go

go:
  - "1.10"

env:
  - GIMME_OS=linux GIMME_ARCH=amd64 PROJECT_NAME=go4microservice2azurekvbyenv CLUSTER_NAME=RelayServicesTest
#  - GIMME_OS=darwin GIMME_ARCH=amd64
#  - GIMME_OS=windows GIMME_ARCH=amd64

# Install services
services:
  - docker

before_install:
  -chmod +x ./deploy/deploy-test.sh

install:
  - go get -d -v ./...

script:
  - go build -v ./cmd/keyvault/
  - go test -v ./test/

#branch: master  => deploy-prod.sh
#branch: staging => deploy-staging.sh 
#branch: dev     => deploy-test.sh
deploy:
  - provider: script
    script: ./deploy/deploy-test.sh
    skip_cleanup: true
    on: 
      branch: master