
dist: xenial

sudo: required

language: go

go:
  - "1.10"

env:
  - GIMME_OS=linux GIMME_ARCH=amd64 PROJECT_NAME=go4microservice2azurekvbyenv CLUSTER_NAME=RelayServicesTest
#  - GIMME_OS=darwin GIMME_ARCH=amd64
#  - GIMME_OS=windows GIMME_ARCH=amd64

# Install services
services:
  - docker

addons:
  apt:
    sources: 
      - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ bionic main'
        key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
      - apt-transport-https
      - azure-cli

before_install:
  - chmod +x ./deploy-test.sh
#  - AZ_REPO=$(lsb_release -cs)
#  - sudo echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list
#  - sudo curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key --yes add -
#  - sudo apt-get --yes install apt-transport-https
#  - sudo apt-get --yes install azure-cli
#  - curl -L https://aka.ms/InstallAzureCli | bash

install:
#  - go get -d -v ./...

#script:
#  - go build -v ./cmd/keyvault/
#  - go test -v ./test/
#echo "stest"

#branch: master  => deploy-prod.sh
#branch: staging => deploy-staging.sh 
#branch: dev     => deploy-test.sh
deploy:
  - provider: script
    script: ./deploy-test.sh
    skip_cleanup: true
    on: 
      branch: master