
language: go

go:
  - "1.10"

env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=amd64
  - PROJECT_NAME=go4microservice2azurekvbyenv
  - CLUSTER_NAME=RelayServicesTest

# Install services
services:
  - docker
 
install:
  - go get -d -v ./...

script:
  - go build -v ./...
  - go test -v ./...