apiVersion: v1
kind: Service
metadata:
  name: go4microservice2azurekvbyenv
  labels:
    app: go4microservice2azurekvbyenv
spec:
   type: LoadBalancer
   ports:
   - port: 8989
     targetPort: 8080
     protocol: TCP
     name: http
   selector:
      app: go4microservice2azurekvbyenv
   